version: '3.8'

services:

  apartment-postgres:
    container_name: apartment-postgres
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  postgres_db:
    driver: local
