"""Added collector and counter models

Revision ID: bd6bc361afd2
Revises: 
Create Date: 2023-04-18 16:58:54.987537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd6bc361afd2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collector_counters',
    sa.Column('Counter id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('Counter id')
    )
    op.create_table('collectors',
    sa.Column('Collector id', sa.Integer(), nullable=False),
    sa.Column('Collector name', sa.String(length=200), nullable=True),
    sa.Column('Collector description', sa.String(length=200), nullable=True),
    sa.Column('Downloading status', sa.Enum('accepted', 'processing', 'error', 'finished', name='statustype'), nullable=True),
    sa.Column('Image search engine', sa.Enum('google', name='searchenginetype'), nullable=True),
    sa.Column('Total number of images to download', sa.Integer(), nullable=True),
    sa.Column('Image storage', sa.Enum('aws', name='storagetype'), nullable=True),
    sa.Column('Search query', sa.String(length=100), nullable=True),
    sa.Column('Maximum time to collect images', sa.Integer(), nullable=True),
    sa.Column('Created at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('Collector id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collectors')
    op.drop_table('collector_counters')
    # ### end Alembic commands ###
